app_name = "gnu_terry_pratchett"
app_title = "Gnu Terry Pratchett"
app_publisher = "BuFf0k"
app_description = "An implementation of the GNU- Tery Pratchett Project for Frappe, injects X-Clacks-Overhead header in pages"
app_email = "buff0k@gmail.com"
app_license = "gpl-2.0"
app_logo_url = "/assets/gnu_terry_pratchett/images/GNU-tp-logo.png"
after_install = "gnu_terry_pratchett.install.after_install"
after_request = ["gnu_terry_pratchett.clacks.inject_clacks_overhead_header"]
